{
    "name": "Custom Demo",
    "version": "1.0",
    "depends": ["base"],
    "author": "Generated by ChatGPT",
    "category": "Tools",
    "summary": "A simple demo module for Odoo 18",
    "description": "This is a basic custom module that adds a simple model and menu.",
    "data": [
        "views/custom_demo_views.xml",
        "views/custom_demo_menu.xml"
    ],
    "installable": True,
    "application": True
}
